dubbo:
  application:
    # 应用名称
    name: rical.usercenter
    id: rical.usercenter
  registry:
    # 注册中心地址
    address: nacos://172.18.2.1:8848/
  protocol:
    # 传输协议
    name: dubbo
    # ip不可为127.0.0.1 -> 本机ip
    host: 172.18.3.1
    # 随机端口
    port: -1
